const Common = () => {
  return (
    <>
      <h1>Ranged Weapons</h1>
      <table>
        <tr>
          <td>
            Name
          </td>
          <td>
            Accuracy
          </td>
          <td>
            Damage (effort)
          </td>
          <td>
            Inventory slots
          </td>
          <td>
            Cost
          </td>
          <td>
            Notes
          </td>
        </tr>
        <tr>
          <td>
            Rock
          </td>
          <td>
            0
          </td>
          <td>
            1d4
          </td>
          <td>
            1
          </td>
          <td>
            0
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Sling
          </td>
          <td>
            0
          </td>
          <td>
            1d6
          </td>
          <td>
            1
          </td>
          <td>
            1
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Short Bow
          </td>
          <td>
            +0
          </td>
          <td>
            1d6
          </td>
          <td>
            1
          </td>
          <td>
            1
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Long Bow
          </td>
          <td>
            +0
          </td>
          <td>
            1d8
          </td>
          <td>
            1
          </td>
          <td>
            2
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Composite Bow
          </td>
          <td>
            +2
          </td>
          <td>
            1d8+2
          </td>
          <td>
            1
          </td>
          <td>
            8
          </td>
          <td>
          </td>
        </tr>
      </table>

      <h1>Meele Weapons</h1>

      <table>
        <tr>
          <td>
            Name
          </td>
          <td>
            Accuracy
          </td>
          <td>
            Damage (effort)
          </td>
          <td>
            Inventory slots
          </td>
          <td>
            Cost
          </td>
          <td>
            Notes
          </td>
        </tr>
        <tr>
          <td>
            Cudgel
          </td>
          <td>
            0
          </td>
          <td>
            1d4
          </td>
          <td>
            1
          </td>
          <td>
            0
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Walking staff
          </td>
          <td>
            0
          </td>
          <td>
            2d4
          </td>
          <td>
            1
          </td>
          <td>
            0
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Hand Axe
          </td>
          <td>
            0
          </td>
          <td>
            1d6+1
          </td>
          <td>
            1
          </td>
          <td>
            1
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Battle Axe
          </td>
          <td>
            0
          </td>
          <td>
            1d8+1
          </td>
          <td>
            1
          </td>
          <td>
            2
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Great Axe
          </td>
          <td>
            0
          </td>
          <td>
            2d8+2
          </td>
          <td>
            2
          </td>
          <td>
            3
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Mace
          </td>
          <td>
            0
          </td>
          <td>
            1d6
          </td>
          <td>
            1
          </td>
          <td>
            1
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Flail
          </td>
          <td>
            0
          </td>
          <td>
            1d8
          </td>
          <td>
            1
          </td>
          <td>
            1
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Morningstar
          </td>
          <td>
            0
          </td>
          <td>
            1d8+1
          </td>
          <td>
            1
          </td>
          <td>
            2
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Knife
          </td>
          <td>
            0
          </td>
          <td>
            1d4+1
          </td>
          <td>
            1
          </td>
          <td>
            1
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Dagger
          </td>
          <td>
            +1
          </td>
          <td>
            1d6
          </td>
          <td>
            1
          </td>
          <td>
            2
          </td>
          <td>
            Durable
          </td>
        </tr>
        <tr>
          <td>
            Sword
          </td>
          <td>
            +1
          </td>
          <td>
            1d8
          </td>
          <td>
            1
          </td>
          <td>
            3
          </td>
          <td>
            Durable
          </td>
        </tr>
        <tr>
          <td>
            Great sword
          </td>
          <td>
            +1
          </td>
          <td>
            2d8
          </td>
          <td>
            2
          </td>
          <td>
            5
          </td>
          <td>
            Durable
          </td>
        </tr>
        <tr>
          <td>
            Spear
          </td>
          <td>
            0
          </td>
          <td>
            2d6
          </td>
          <td>
            2
          </td>
          <td>
            1
          </td>
          <td>
            Reach
          </td>
        </tr>
        <tr>
          <td>
            Halberd
          </td>
          <td>
            0
          </td>
          <td>
            2d8
          </td>
          <td>
            2
          </td>
          <td>
            3
          </td>
          <td>
            Reach
          </td>
        </tr>
      </table>

      <h1>Armor</h1>

      <table>
        <tr>
          <td>
            Name
          </td>
          <td>
            Defense
          </td>
          <td>
            Inventory slots
          </td>
          <td>
            Cost
          </td>
          <td>
            Notes
          </td>
        </tr>
        <tr>
          <td>
            Padded armor
          </td>
          <td>
            +1
          </td>
          <td>
            1
          </td>
          <td>
            2
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Armored Clothing
          </td>
          <td>
            +1
          </td>
          <td>
            1
          </td>
          <td>
            7
          </td>
          <td>
            On the surface looks like normal clothing
          </td>
        </tr>
        <tr>
          <td>
            Leather armor
          </td>
          <td>
            +2
          </td>
          <td>
            2
          </td>
          <td>
            4
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Ring mail
          </td>
          <td>
            +3
          </td>
          <td>
            2
          </td>
          <td>
            6
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Scale mail
          </td>
          <td>
            +4
          </td>
          <td>
            3
          </td>
          <td>
            8
          </td>
          <td>
          </td>
        </tr>
        <tr>
          <td>
            Plate armor
          </td>
          <td>
            +5
          </td>
          <td>
            3
          </td>
          <td>
            10
          </td>
          <td>
          </td>
        </tr>
      </table>
    </>
  );
};

export default Common;