function LevelUpRollTable() {
    return (
        <>
          <table>
            <tr>
                <td>
                    1
                </td>
                <td>
                    +1 Heart, raise your hit points by 5.
                </td>
            </tr>
            <tr>
                <td>
                    2
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    3
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    4
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    5
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    6
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    7
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    8
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    9
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    10
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    11
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    12
                </td>
                <td>
                </td>
            </tr>
          </table>
        </>
      );
  }
  
  export default LevelUpRollTable;